### ISSUE TITLE
Inline constructor invocations

### ISSUE THREAD

**Issue by andyfriesen** [cruxlang/crux#92] opened 2016-04-11 22:45 UTC
`let a = Some(44)`

presently compiles to something like

```
function Some(x) { return ['Some', x]; }
var a = Some(44)
```

But it could be compiled to this instead:
```
var a = ['Some', 44];
```

**Comment by chadaustin** [comment] 2016-07-27 07:29
I think a generalized inliner will take care of this handily.  Filing a new issue for that.  Also, we'll need to play with different sum representations in JS so we benefit from V8 shapes.  cc @kg

Closing as duplicate of #126.

**Closed by chadaustin** 2016-07-27 07:29 UTC

**Comment by kg** [comment] 2016-07-27 19:07
The best way to get shapes for this would be JS objects with named properties where the values have been type hinted, I think. Heterogeneous arrays don't have efficient representations AFAIK and the elements will probably not have known type info (other than at specific ICs that only access predictably-typed elements). You might benefit from defining the objects as named types with getters so the getters can have strongly typed return values.
